name: full stack ci cd pipeline

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Test full stack application
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'

      - name: Set up React js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: install python dependecies
        run: |
          cd quore_clone/quore_clone
          python -m pip install psycopg2-binary
          pip install -r requirements.txt
         
      
      - name: Install react dependencies
        run: |
          cd frontend/frontend
          npm install
      
      - name: build frontend
        run: |
          cd frontend/frontend
          npm run build

      

      

